<meta http-equiv="Content-type" content="text/html; charset=utf-8" />

<style>
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    div#welcome
    {
        color: #FFFFFF;
        background-color: black;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    .button_search
    {

        background-color: green;
        color:white;
        height:30px;

    }

    div#more-information
    {
        background-color:white;
        height: 100%;
    }
</style>
<form name="formRequest" id="formRequest" method="post" action="<?=$this->baseUrl('Request')?>">
    <div id="welcome">
        <h1>Aplicação que realiza requisição e salva os dados no banco de dados</h1>

        <h3>Clique em pesquisar para fazer a requisição e armazenar os dados do CNPJ - 31.804.115-0002-43</h3>

        <div id="more-information">
            <p><input type="submit" name="request" id="request" value="Pesquisar e Armazenar" class="button_search"></p>
        </div>
    </div>
</form>